<head>
<script type="text/javascript" src="../scr/calendar.js"></script>
<script type="text/javascript" src="../scr/lang/calendar-<%=Left(Session("myLng"), 2)%>.js"></script>
<script type="text/javascript" src="../scr/calendar-setup.js"></script>
<script language="javascript" src="../general.js"></script>

<link rel="stylesheet" type="text/css" media="all" href="../design/0/style/style_cal.css" title="winter" />
<style>
input
{
	font-family: verdana; font-size: 10px; border-style: solid; border-width: 1px; background-color: #E1EFFD;
}
select
{
	font-family: verdana; font-size: 10px; border-style: solid; border-width: 1px; background-color: #E1EFFD;
}

</style>


</head>





