<%
Dim myLanIndex(10)
Dim myLanItm(5)

myLanItm(0) = "en"
myLanItm(1) = "English (United States)"
myLanItm(2) = "en"
myLanItm(3) = "ltr"
myLanItm(4) = "1"
myLanItm(5) = "us_english"
myLanIndex(0) = myLanItm

myLanItm(0) = "en-uk"
myLanItm(1) = "English (United Kingdom)"
myLanItm(2) = "en-uk"
myLanItm(3) = "ltr"
myLanItm(4) = "4"
myLanItm(5) = "uk_english"
myLanIndex(1) = myLanItm

myLanItm(0) = "es"
myLanItm(1) = "Espa&#241;ol (Latinoam&#233;rica)"
myLanItm(2) = "es"
myLanItm(3) = "ltr"
myLanItm(4) = "2"
myLanItm(5) = "Spanish"
myLanIndex(2) = myLanItm

myLanItm(0) = "fr"
myLanItm(1) = "Fran&#231;ais"
myLanItm(2) = "fr"
myLanItm(3) = "ltr"
myLanItm(4) = "8"
myLanItm(5) = "French"
myLanIndex(3) = myLanItm

myLanItm(0) = "pt"
myLanItm(1) = "Portugu&#234;s (Brazil)"
myLanItm(2) = "pt-br"
myLanItm(3) = "ltr"
myLanItm(4) = "6"
myLanItm(5) = "Brazilian"
myLanIndex(4) = myLanItm

myLanItm(0) = "cs"
myLanItm(1) = "&#268;e&#353;tina"
myLanItm(2) = "de"
myLanItm(3) = "ltr"
myLanItm(4) = "14"
myLanItm(5) = "Czech"
myLanIndex(5) = myLanItm

myLanItm(0) = "sk"
myLanItm(1) = "Slovenský"
myLanItm(2) = "sk"
myLanItm(3) = "ltr"
myLanItm(4) = "16"
myLanItm(5) = "Slovak"
myLanIndex(6) = myLanItm

myLanItm(0) = "de"
myLanItm(1) = "Deutsch"
myLanItm(2) = "de"
myLanItm(3) = "ltr"
myLanItm(4) = "10"
myLanItm(5) = "German"
myLanIndex(7) = myLanItm

myLanItm(0) = "pl"
myLanItm(1) = "Polska"
myLanItm(2) = "pl"
myLanItm(3) = "ltr"
myLanItm(4) = "15"
myLanItm(5) = "Polish"
myLanIndex(8) = myLanItm

myLanItm(0) = "ru"
myLanItm(1) = "&#1056;&#1091;&#1089;&#1089;&#1082;&#1080;&#1081;"
myLanItm(2) = "ru"
myLanItm(3) = "ltr"
myLanItm(4) = "13"
myLanItm(5) = "Russian"
myLanIndex(9) = myLanItm

myLanItm(0) = "he"
myLanItm(1) = "&#1506;&#1489;&#1512;&#1497;&#1514;"
myLanItm(2) = "he"
myLanItm(3) = "rtl"
myLanItm(4) = "3"
myLanItm(5) = "us_english"
myLanIndex(10) = myLanItm

%>