<table border="0" cellpadding="0" cellspacing="0" width="700" dir="ltr">
  <tr>
   <td><img src="inc/HE/spacer.gif" width="43" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="87" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="194" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="8" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="31" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="308" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="29" height="1" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>

  <tr>
   <td colspan="5" align="right"><img name="online_kit_art2_r1_c1" src="inc/HE/online_kit_art2_r1_c1.jpg" width="363" height="211" border="0" alt=""></td>
   <td colspan="2"><img name="online_kit_art2_r1_c6" src="inc/HE/online_kit_art2_r1_c6.jpg" width="337" height="211" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="1" height="211" border="0" alt=""></td>
  </tr>
  <tr>
   <td rowspan="5" colspan="4" valign="top">
   <table cellpadding="0" cellspacing="0" border="0" width="100%">
   	<tr>
   		<td rowspan="4">&nbsp;</td>
   		<td rowspan="3" width="130" height="59"><img src="inc/HE/online_kit_art2_r9_c4.jpg"></td>
   		<td width="194" height="19"><a href="admin/" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('btnAdmin','','inc/HE/btnAdminHover.jpg',1);"><img name="btnAdmin" src="inc/HE/btnAdmin.jpg" width="194" height="19" border="0" id="btnAdmin" alt="" /></a></td>
   		<td rowspan="4"><img src="inc/HE/online_kit_art2_r9_c1.jpg" width="8" height="146"></td>
   	</tr>
   	<tr>
   		<td width="194" height="20"><a href="" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('btnStore','','inc/HE/btnStoreHover.jpg',1);"><img name="btnStore" src="inc/HE/btnStore.jpg" width="194" height="20" border="0" id="btnStore" alt="" /></a></td>
   	</tr>
   	<tr>
   		<td width="194" height="19"><a href="mobile/" onmouseout="MM_swapImgRestore();" onmouseover="MM_swapImage('btnPocket','','inc/HE/btnPocketHover.jpg',1);"><img name="btnPocket" src="inc/HE/btnPocket.jpg" width="194" height="19" border="0" id="btnPocket" alt="" /></a></td>
   	</tr>
   	<tr>
   		<td width="324" height="87" colspan="2"><img src="inc/HE/online_kit_art2_r9_c3.jpg"></td>
   	</tr>
   </table>
   </td>
   <td rowspan="5" colspan="3"><img name="online_kit_art2_r2_c5" src="inc/HE/online_kit_art2_r2_c5.jpg" width="368" height="146" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img src="inc/HE/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img src="inc/HE/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img src="inc/HE/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td><img src="inc/HE/spacer.gif" width="1" height="88" border="0" alt=""></td>
  </tr>
  <tr>
   <td rowspan="3">&nbsp;</td>
   <td colspan="5" background="inc/HE/online_kit_art2_r7_c2.jpg" align="right"><font color="#016AA3" size="2" face="Tahoma"><span dir="rtl"><%=getintroLngStr("LtxtOLKNote")%></span></font></td>
   <td rowspan="3" background="inc/HE/online_kit_art2_r7_c7.jpg" valign="bottom" align="center">
	<table cellpadding="0" cellspacing="0" border="0" align="center">
		<tr>
			<td width="27" align="right" style="padding-right: 10px; padding-top: 2px;" valign="top">
				<table cellpadding="0" cellspacing="0" border="0" style="cursor: hand" onclick="return !showSelectLang(this, event);" style="border: solid 1px #016AA3;">
				<tr>
					<td width="16" height="16" align="center">
					<font size="1" face="Verdana" color="#016AA3"><%=LEFT(UCase(Session("myLng")), 2)%></font></td>
				</tr>
				</table>
			</td>
	 	 </tr>
	   </table>
	</td>
   <td><img src="inc/HE/spacer.gif" width="1" height="106" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="5"><img name="online_kit_art2_r8_c2" src="inc/HE/online_kit_art2_r8_c2.jpg" width="628" height="11" border="0" alt=""></td>
   <td><img src="inc/HE/spacer.gif" width="1" height="11" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="5" background="inc/HE/online_kit_art2_r9_c2.jpg" width="628" height="26" align="center" dir="rtl"><%=txtFootNote%></td>
   <td><img src="inc/HE/spacer.gif" width="1" height="26" border="0" alt=""></td>
  </tr>
</table>
