<table border="0" cellpadding="0" cellspacing="0" width="700">
  <tr>
   <td><img src="inc/ES/spacer.gif" width="43" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="289" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="8" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="23" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="170" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="138" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="29" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>

  <tr>
   <td colspan="4"><img name="online_kit_art2_r1_c1" src="inc/ES/online_kit_art2_r1_c1.jpg" width="363" height="211" border="0" alt=""></td>
   <td colspan="3"><img name="online_kit_art2_r1_c5" src="inc/ES/online_kit_art2_r1_c5.jpg" width="337" height="211" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="211" border="0" alt=""></td>
  </tr>
  <tr>
   <td rowspan="5" colspan="2"><img name="online_kit_art2_r2_c1" src="inc/ES/online_kit_art2_r2_c1.jpg" width="332" height="146" border="0" alt=""></td>
   <td rowspan="5"><img name="online_kit_art2_r2_c3" src="inc/ES/online_kit_art2_r2_c3.jpg" width="8" height="146" border="0" alt=""></td>
   <td colspan="2"><a href="admin/" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('btnAdmin','','inc/ES/btnAdminHover.jpg',1);"><img name="btnAdmin" src="inc/ES/btnAdmin.jpg" width="193" height="19" border="0" alt=""></a></td>
   <td rowspan="5" colspan="2"><img name="online_kit_art2_r2_c6" src="inc/ES/online_kit_art2_r2_c6.jpg" width="167" height="146" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="2"><a href="" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('btnStore','','inc/ES/btnStoreHover.jpg',1);"><img name="btnStore" src="inc/ES/btnStore.jpg" width="193" height="19" border="0" alt=""></a></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="2"><img name="online_kit_art2_r4_c4" src="inc/ES/online_kit_art2_r4_c4.jpg" width="193" height="1" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="1" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="2"><a href="mobile/" onMouseOut="MM_swapImgRestore();" onMouseOver="MM_swapImage('btnPocket','','inc/ES/btnPocketHover.jpg',1);"><img name="btnPocket" src="inc/ES/btnPocket.jpg" width="193" height="19" border="0" alt=""></a></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="19" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="2"><img name="online_kit_art2_r6_c4" src="inc/ES/online_kit_art2_r6_c4.jpg" width="193" height="88" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="88" border="0" alt=""></td>
  </tr>
  <tr>
   <td rowspan="3"><img name="online_kit_art2_r7_c1" src="inc/ES/online_kit_art2_r7_c1.jpg" width="43" height="143" border="0" alt=""></td>
   <td colspan="5" background="inc/ES/online_kit_art2_r7_c2.jpg"><font color="#016AA3" size="2" face="Tahoma"><%=getintroLngStr("LtxtOLKNote")%></font></td>
   <td rowspan="3" valign="bottom" align="center">
   <table cellpadding="0" cellspacing="0" border="0" align="center">
   	<tr>
		<td width="27" align="right" style="padding-right: 10px; padding-top: 2px;" valign="top">
			<table cellpadding="0" cellspacing="0" border="0" style="cursor: hand" onclick="return !showSelectLang(this, event);" style="border: solid 1px #016AA3;">
			<tr>
				<td width="16" height="16" align="center">
				<font size="1" face="Verdana" color="#016AA3"><%=LEFT(UCase(Session("myLng")), 2)%></font></td>
			</tr>
			</table>
		</td>
	</tr>
   </table>
   </td>
   <td><img src="inc/ES/spacer.gif" width="1" height="106" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="5"><img name="online_kit_art2_r8_c2" src="inc/ES/online_kit_art2_r8_c2.jpg" width="628" height="11" border="0" alt=""></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="11" border="0" alt=""></td>
  </tr>
  <tr>
   <td colspan="5" align="center"><%=txtFootNote%></td>
   <td><img src="inc/ES/spacer.gif" width="1" height="26" border="0" alt=""></td>
  </tr>
</table>