<div id="dvValueSelect">&nbsp;
<div style="height: 536px; overflow: auto; background-color: #FFFFFF; position: relative; " id="dvValueSelectContent">
<table border="0" cellpadding="0" width="100%">
	<tr class="GeneralTlt">
		<td><span id="dvValueSelectTitle">Title</span></td>
	</tr>
	<tr>
		<td>
		<table border="0" width="100%" id="tblValueSelectData" cellpadding="0">
		</table>
		</td>
	</tr>
</table>
</div>
</div>
